version: "3"

volumes:
  mongodb-data:

services:
  frontend:
    build: ./frontend
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    links:
      - database
      - filesystem
    depends_on:
      - database
      - filesystem
    environment:
      - MONGO_USERNAME=mongo
      - MONGO_PASSWORD=password
      - MONGO_HOST=database
      - MONGO_PORT=27017

  filesystem:
    build: ./filesystem
    working_dir: /app
    ports:
      - 8000:8000
    volumes:
      - ./filesystem/:/app
    links:
      - database
    depends_on:
      - database
    environment:
      - MONGO_USERNAME=mongo
      - MONGO_PASSWORD=password
      - MONGO_IP=database
      - MONGO_PORT=27017

  database:
    image: mongo:5-focal
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
